"""remove unused User.image_file column

Revision ID: 0107eeb3e2e8
Revises: 78ed529a81f4
Create Date: 2026-09-21 20:07:01.711493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0107eeb3e2e8'
down_revision: Union[str, Sequence[str], None] = '78ed529a81f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_file', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
