"""add master_services many-to-many table

Revision ID: 0e324f335107
Revises: 0107eeb3e2e8
Create Date: 2026-09-23 16:16:11.390687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e324f335107'
down_revision: Union[str, Sequence[str], None] = '0107eeb3e2e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_id', 'service_id', name='uq_master_service')
    )
    op.create_index(op.f('ix_master_services_id'), 'master_services', ['id'], unique=False)
    op.create_index(op.f('ix_master_services_master_id'), 'master_services', ['master_id'], unique=False)
    op.create_index(op.f('ix_master_services_service_id'), 'master_services', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_services_service_id'), table_name='master_services')
    op.drop_index(op.f('ix_master_services_master_id'), table_name='master_services')
    op.drop_index(op.f('ix_master_services_id'), table_name='master_services')
    op.drop_table('master_services')
    # ### end Alembic commands ###
