"""add booking_horizon_days to organization

Revision ID: 22d1d8780738
Revises: ea2ed59bef23
Create Date: 2026-09-24 14:59:22.881249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d1d8780738'
down_revision: Union[str, Sequence[str], None] = 'ea2ed59bef23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('booking_horizon_days', sa.Integer(),
                                             nullable=False, server_default='30'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'booking_horizon_days')
    # ### end Alembic commands ###
