"""add client comments

Revision ID: 47fb59884ad5
Revises: ef9906927673
Create Date: 2026-09-30 12:38:01.510437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47fb59884ad5'
down_revision: Union[str, Sequence[str], None] = 'ef9906927673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_comments_client_id'), 'client_comments', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_comments_id'), 'client_comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_comments_id'), table_name='client_comments')
    op.drop_index(op.f('ix_client_comments_client_id'), table_name='client_comments')
    op.drop_table('client_comments')
    # ### end Alembic commands ###
