"""make client phone uniqueness partial (exclude soft-deleted)

Revision ID: 4cbfccf85016
Revises: 73424a0960df
Create Date: 2026-09-19 21:36:19.126600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cbfccf85016'
down_revision: Union[str, Sequence[str], None] = '73424a0960df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_client_phone_per_org'), 'clients', type_='unique')
    op.create_index('uq_client_phone_per_org_active', 'clients', ['organization_id', 'phone'], unique=True, postgresql_where='deleted_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_client_phone_per_org_active', table_name='clients', postgresql_where='deleted_at IS NULL')
    op.create_unique_constraint(op.f('uq_client_phone_per_org'), 'clients', ['organization_id', 'phone'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
