"""initial schema

Revision ID: 73424a0960df
Revises: 
Create Date: 2026-09-15 19:55:19.547609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73424a0960df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'invitations', 'masters', ['master_id'], ['id'])
    op.create_foreign_key(None, 'memberships', 'masters', ['master_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    # ### end Alembic commands ###
