"""add TimeOff and WorkingHoursException models

Revision ID: ea2ed59bef23
Revises: 0e324f335107
Create Date: 2026-09-24 14:42:16.140135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea2ed59bef23'
down_revision: Union[str, Sequence[str], None] = '0e324f335107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_off',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_off_id'), 'time_off', ['id'], unique=False)
    op.create_index(op.f('ix_time_off_master_id'), 'time_off', ['master_id'], unique=False)
    op.create_table('working_hours_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_id', 'date', 'start_time', name='uq_master_exception_slot')
    )
    op.create_index(op.f('ix_working_hours_exceptions_date'), 'working_hours_exceptions', ['date'], unique=False)
    op.create_index(op.f('ix_working_hours_exceptions_id'), 'working_hours_exceptions', ['id'], unique=False)
    op.create_index(op.f('ix_working_hours_exceptions_master_id'), 'working_hours_exceptions', ['master_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_working_hours_exceptions_master_id'), table_name='working_hours_exceptions')
    op.drop_index(op.f('ix_working_hours_exceptions_id'), table_name='working_hours_exceptions')
    op.drop_index(op.f('ix_working_hours_exceptions_date'), table_name='working_hours_exceptions')
    op.drop_table('working_hours_exceptions')
    op.drop_index(op.f('ix_time_off_master_id'), table_name='time_off')
    op.drop_index(op.f('ix_time_off_id'), table_name='time_off')
    op.drop_table('time_off')
    # ### end Alembic commands ###
