"""add organization timezone

Revision ID: f684aeeaf725
Revises: f9e4dd898d7a
Create Date: 2026-09-26 14:34:31.733184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f684aeeaf725'
down_revision: Union[str, Sequence[str], None] = 'f9e4dd898d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('timezone',
                                             sa.String(length=50),
                                             nullable=False,
                                             server_default='UTC'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'timezone')
    # ### end Alembic commands ###
